
#include <windows.h>

// Edits IDs in EditsStore
// All to enum?..
#define MECHOUS_PARAM_SCALE_SIZE		0
#define MECHOUS_PARAM_SCALE_BOUND		1
#define MECHOUS_PARAM_SCALE_BOX			2

#define MECHOUS_PARAM_MASS_OFF_Z		3

#define MECHOUS_PARAM_SPEED				4
#define MECHOUS_PARAM_SPEED_WATER		5
#define MECHOUS_PARAM_SPEED_AIR			6
#define MECHOUS_PARAM_SPEED_MOLE		7
#define MECHOUS_PARAM_MOBILITY			8

#define MECHOUS_PARAM_ARCHIMEDIAN		9
#define MECHOUS_PARAM_WATER_TRACTION	10
#define MECHOUS_PARAM_WATER_RUDDER		11

#define MECHOUS_PARAM_TERRA_MOVER_X		12
#define MECHOUS_PARAM_TERRA_MOVER_Y		13
#define MECHOUS_PARAM_TERRA_MOVER_Z		14

#define MECHOUS_PARAM_DEFENCE_FRONT		15
#define MECHOUS_PARAM_DEFENCE_BACK		16
#define MECHOUS_PARAM_DEFENCE_SIDE		17
#define MECHOUS_PARAM_DEFENCE_TOP		18
#define MECHOUS_PARAM_DEFENCE_BOTTOM	19

#define MECHOUS_PARAM_RAM_FRONT			20
#define MECHOUS_PARAM_RAM_BACK			21
#define MECHOUS_PARAM_RAM_SIDE			22
#define MECHOUS_PARAM_RAM_TOP			23
#define MECHOUS_PARAM_RAM_BOTTOM		24

#define MECHOUS_PARAM_COLOR_OFFSET		25
#define MECHOUS_PARAM_COLOR_SHIFT		26

#define MECHOUS_PARAM_ANGLE_LIMIT		27
#define MECHOUS_PARAM_WELD_LIMIT		28

#define MECHOUS_PARAMS_COUNT			29

extern float *MechousParams;
BOOL CreateMechousParamsWindow(HINSTANCE hInstance, HWND Parent);